### ISSUE TITLE
ROS Indigo

### ISSUE THREAD

**Issue by davisoa** [kth-ros-pkg/biotac_driver#4]
I have added a branch to support ROS Indigo, and also the ability to have more than one Cheetah attached to a computer at a time, but since there isn't an Indigo branch here, I can't create a pull request to give you this code.  You can find my fork with the changes here: https://github.com/davisoa/biotac_driver

**Comment by diogoalmeida** [comment]
Thank you so much! I've made an 'indigo' branch with your changes.
